// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXb4ful2CMhPj59lU9w8KkE6-Et7lkNY4',
    appId: '1:751816778677:web:115cd37965678493d2affc',
    messagingSenderId: '751816778677',
    projectId: 'evently-app-2025',
    authDomain: 'evently-app-2025.firebaseapp.com',
    storageBucket: 'evently-app-2025.firebasestorage.app',
    measurementId: 'G-R52C010Z9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfubwjvFEH8jofY5xtn-pE3ZFSMXbj0o',
    appId: '1:751816778677:android:862ebc89778d0c39d2affc',
    messagingSenderId: '751816778677',
    projectId: 'evently-app-2025',
    storageBucket: 'evently-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdrFGDJFbyV-gNLu4I0IwTpj49XZiJucQ',
    appId: '1:751816778677:ios:bde2bbb0effa6ff9d2affc',
    messagingSenderId: '751816778677',
    projectId: 'evently-app-2025',
    storageBucket: 'evently-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdrFGDJFbyV-gNLu4I0IwTpj49XZiJucQ',
    appId: '1:751816778677:ios:bde2bbb0effa6ff9d2affc',
    messagingSenderId: '751816778677',
    projectId: 'evently-app-2025',
    storageBucket: 'evently-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXb4ful2CMhPj59lU9w8KkE6-Et7lkNY4',
    appId: '1:751816778677:web:fd01c1177ffa657bd2affc',
    messagingSenderId: '751816778677',
    projectId: 'evently-app-2025',
    authDomain: 'evently-app-2025.firebaseapp.com',
    storageBucket: 'evently-app-2025.firebasestorage.app',
    measurementId: 'G-L7V4J44HK3',
  );
}
